const UP_RIGHT_CORNER = 1
const UP_LEFT_CORNER = 2
const DOWN_LEFT_CORNER = 3
const DOWN_RIGHT_CORNER = 4
const UP_LINE = 5
const LEFT_LINE = 6
const DOWN_LINE = 7
const RIGHT_LINE = 8 
const MIDLE = 9

export {
    UP_RIGHT_CORNER,
    UP_LEFT_CORNER,
    DOWN_LEFT_CORNER,
    DOWN_RIGHT_CORNER,
    UP_LINE,
    LEFT_LINE,
    DOWN_LINE,
    RIGHT_LINE,
    MIDLE
}